import io
import zipfile


def generate_brand_kit_zip(
    business_name: str,
    logo_svg: str,
    website_html: str,
    brand_guide: str,
    social_posts: dict,
    seo_tags: dict,
    colors: dict,
) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("logo.svg", logo_svg)
        zf.writestr("website.html", website_html)

        social_text = f"""Social Media Posts - {business_name}
{'=' * 50}

Twitter/X:
{social_posts.get('twitter', '')}

LinkedIn:
{social_posts.get('linkedin', '')}

Instagram:
{social_posts.get('instagram', '')}
"""
        zf.writestr("social-posts.txt", social_text)

        seo_text = f"""SEO Metadata - {business_name}
{'=' * 50}

Title: {seo_tags.get('title', '')}
Description: {seo_tags.get('description', '')}
Keywords: {', '.join(seo_tags.get('keywords', []))}
OG Title: {seo_tags.get('og_title', '')}
OG Description: {seo_tags.get('og_description', '')}
"""
        zf.writestr("seo-metadata.txt", seo_text)

        zf.writestr("brand-guide.md", brand_guide)

        readme = f"""# {business_name} - Brand Kit

Generated by Solivagant AI Brand Designer

## Contents
- logo.svg - Brand logo (SVG)
- website.html - Complete landing page
- brand-guide.md - Full brand guidelines
- social-posts.txt - Social media copy
- seo-metadata.txt - SEO metadata

## Colors
- Primary: {colors.get('primary', '')}
- Secondary: {colors.get('secondary', '')}
- Accent: {colors.get('accent', '')}
- Background: {colors.get('background', '')}
- Text: {colors.get('text', '')}
"""
        zf.writestr("README.md", readme)

    return buf.getvalue()
